# Generated by Django 4.1.7 on 2023-03-19 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='emailAddress',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
