# Generated by Django 4.1.7 on 2023-03-19 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_contact_emailaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='emailAddress',
            field=models.CharField(max_length=122),
        ),
    ]
